apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-runtime
  namespace: streaming
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-orchestrator
  namespace: streaming
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: producer
  namespace: streaming
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard
  namespace: streaming

